# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JobFair' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JobFair
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'Reusable' 
  pod 'SwiftLint'
  pod 'RxSwiftExt'
  pod 'RxDataSources'
  pod 'RxAlamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Then'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'AccountKit'
  pod 'MJRefresh', '3.1'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD', '1.1'
  pod 'SDWebImage', '4.4'

  target 'JobFairTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JobFairUITests' do
    # Pods for testing
  end

end
