# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JobFair' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JobFair
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'Reusable' 

  target 'JobFairTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JobFairUITests' do
    # Pods for testing
  end

end
